services:
  - type: web
    name: purple-music-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    plan: free
    region: frankfurt
    branch: main
    envVars:
      - key: PORT
        value: 10000
      - key: PI_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SUPABASE_URL
        value: https://ofkfygqrfenctzitigae.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://purplemusictestnet.netlify.app
      - key: NODE_ENV
        value: production
